### ISSUE TITLE
Bower warning about the "main" field

### ISSUE THREAD

**Issue by abkieling** [hawtio/hawtio-utilities#11]
When installing hawtio-utilities using Bower, the following message is printed:

bower hawtio-utilities#~2.0.0                invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .js files: ["dist/angular-file-upload.js","dist/hawtio-utilities.js"]

Bower expects only one main JavaScript file. A solution would be concatenating the two files into one.

**Comment by tadayosi** [comment]
Should be out of date.
