### ISSUE TITLE
hawtio-utilities requirement for sugarjs not compatible with systemjs/jspm/babel

### ISSUE THREAD

**Issue by kwesterfeld** [hawtio/hawtio-utilities#3]
We are using babel with systemjs and are running into incompatibilities between sugar and redefinition of Object.keys() it does, deep inside the babel transpiler while loading our app.

I've tracked the issue down to hawtio-utilities requiring sugar.js.  As far as I can see, the sugar compatibility is just for a few methods.  Could sugar.js be dropped as a core requirement?  For example, I found that Core.isBlank() calls str.isBlank(), which is simply rewritten as str.trim().length === 0.

I'm not sure how big a job this is, but if its not too much trouble it would really help the modernization effort w.r.t. ES6 and jspm/systemjs.

**Comment by gashcrumb** [comment]
+1, I've personally favored using lodash instead, sugarjs + typescript is kind of a nightmare.

**Comment by kwesterfeld** [comment]
I'm going to send a PR for the one String.isBlank() I found.  Basically,
sugar was probably nice 3+ years ago, but nowadays you simply cannot be
mucking with behavior of the JS core.

Thanks

**Comment by kwesterfeld** [comment]
I found Core.maybePlural() commented to use sugarjs, and `.pluralize()` is not in lodash (b/c the author doesnt want to touch it with a 10-ft pole it looks like).  

I only found hawtio-integration using Core.maybePlural().   Its only english as far as I can see.  Maybe it could move to hawtio-integration?  Or maybe hawtio-integration should do a require() on pluralize?  I'll leave it be for now.  

The angular-gettext project does plurals and translation enablement uber-awesome, so that's an option too.

```

    /**
     * Given values (n, "person") will return either "1 person" or "2 people" depending on if a plural
     * is required using the String.pluralize() function from sugarjs
     * @method maybePlural
     * @for Core
     * @static
     * @param {Number} count
     * @param {String} word
     * @return {String}
     */
    function maybePlural(count, word) {
        var pluralWord = (count === 1) ? word : word.pluralize();
        return "" + count + " " + pluralWord;
    }
    Core.maybePlural = maybePlural;
```

**Comment by gashcrumb** [comment]
given that it's probably for 'queues', 'topics' and 'messages' I could probably update it to just tack on an 's' at the end of the word if count != 1 for now...

**Comment by kwesterfeld** [comment]
I found a few more...I'll send a PR with the three changes (removing
Core.maybePlural(), fixing Core.isBlank(), and fixing Core.join().   It's a
bit bigger than I thought but hopefully not too bad

**Comment by gashcrumb** [comment]
@kwesterfeld thanks, you're the best!

**Comment by kwesterfeld** [comment]
I found Sugar is supplying encodeBase64() for login behavior.  It's a bit of a sweater unravelling.

I'm going to commit progress on my fork and revisit next week.
